ALTER TABLE Users
DROP CONSTRAINT [UQ__Users__536C85E49F8BED66]

ALTER TABLE Users
ADD CONSTRAINT uq_Username UNIQUE (Username)

ALTER TABLE Users
ADD CONSTRAINT CHK_UsernameSize CHECK(DATALENGTH(Username) >= 3)